### ISSUE TITLE
Widget display is empty

### ISSUE THREAD

**Issue by isleshocky77** [osugregor/Google-Events-Widget--ANTP-#1]
I've installed your widget through the store and it displays an empty box.

![screenshot from 2013-09-30 14 37 08](https://f.cloud.github.com/assets/361586/1239715/644f647a-29ff-11e3-82f3-afd36e729b97.png)

I've attached the output of the console

![screenshot from 2013-09-30 14 36 59](https://f.cloud.github.com/assets/361586/1239714/644d89a2-29ff-11e3-9b55-78bb5ab1f63c.png)

**Comment by osugregor** [comment]
Hi Stephen!

First off thanks for contacting me about the issue and providing the information about the blank widget and the console output.
It looks like it might be a case sensitivity problem with filenames, I have updated the file references and uploaded the changes.

Please update to version 2.2.0 and let me know if the issue persists so I can look further into the problem.

To update the widget please goto Settings -> Extensions (chrome://extensions/), check the "Developer mode" checkbox, and click the "Update extensions now" button if automatic updates are disabled.
![screen shot 2013-09-30 at 11 13 27 pm](https://f.cloud.github.com/assets/781984/1242592/199107f6-2a48-11e3-99a9-19944911f62b.png)

I really appreciate the console output, I have seen numerous reviews about the widget being blank, have attempted to contact those users, but never received a reply… Let me know if there are any additions/functionality you would like!

Thanks a ton!
Greg

**Comment by isleshocky77** [comment]
This fixed the issue. Thanks for the prompt reply and release.
