### ISSUE TITLE
Synchronisation stopped working

### ISSUE THREAD

**Issue by Ragbak** [osugregor/Google-Events-Widget--ANTP-#4]
Google changed the url to fetch the calander data and now the widget does not sync anymore.

Failed to load resource: the server responded with a status of 403 (Forbidden)
shayjs.js:96 ERROR: An error was encountered in fetching the feed: Object
shayjs.js:82 [EVENT ShayJS.antp] Storage Changed Storage
shayjs.js:82 [EVENT ShayJS.antp] Storage Changed Storage
shayjs.js:82 [EVENT ShayJS.antp] Storage Changed Storage
background.js:51 Fetching Events...
shayjs.js:84 [Fetching set] true
shayjs.js:84 Fetching list of calendars.

**Comment by Ragbak** [comment]
Is someone even looking after this widget or should I just ditch it? _sadface_

**Comment by osugregor** [comment]
Hey sorry,

Ill try and find time in the next couple of days!

**Comment by Ragbak** [comment]
Sorry to see this is still not working.
Well, was nice to have the tool as long as it worked.
